name: magnet_connects_monorepo
description: "Monorepo root for Magnet Connects (mfresh & mfresh_ops)."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: ^6.0.0
  flutter_lints: ^5.0.0
