name: services
description: "Backend services and logic for Magnet Connects."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Internal Dependencies
  core:
    path: ../core

  # External Dependencies
  get: ^4.7.3
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  firebase_remote_config: ^6.4.0
  flutter_local_notifications: ^20.1.0
  connectivity_plus: ^7.1.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.1.3
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  package_info_plus: ^9.0.1
  envied: ^1.3.4
  crypto: ^3.0.6
  phonepe_payment_sdk: ^2.0.3
  in_app_update_flutter: ^2.0.3
  geolocator: ^13.0.2
  flutter_foreground_task: ^6.3.3
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.3.4
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  hive_ce_generator: ^1.11.1
